language: swift
osx_image: 
    - xcode10.2
    - xcode11.1
xcode_destination:
    - platform=iOS Simulator,OS=8.1,name=iPhone 5
    - platform=iOS Simulator,OS=13.1,name=iPhone 8
xcode_project: PainlessInjection/PainlessInjection.xcodeproj
xcode_scheme: PainlessInjection
after_success:
    - bash <(curl -s https://codecov.io/bash) -t d57dba6a-8e17-4a91-b7bf-ef7abe812e24
