language: swift
osx_image: xcode7
script:
    - xcodebuild clean test -workspace PainlessInjection/PainlessInjection.xcworkspace -scheme PainlessInjection -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)