language: swift
script: set -o pipefail && xcodebuild -project PainlessInjection.xcodeproj -scheme PainlessInjection -destination platform\=iOS\ Simulator,OS\=13.1,name\=iPhone\ 8 build test | xcpretty

# jobs:
#   inclue:
#     - stage: "Tests"
      
#       name: "iOS 13.1"
#     - osx_image: xcode10.2
#       xcode_project: PainlessInjection.xcodeproj
#       xcode_scheme: PainlessInjection
#       xcode_destination: platform=iOS Simulator,OS=8.1,name=iPhone 5
#       name: "iOS 8.1"
after_success:
 - bash <(curl -s https://codecov.io/bash) -t d57dba6a-8e17-4a91-b7bf-ef7abe812e24