language: swift
xcode_project: PainlessInjection.xcodeproj
xcode_scheme: PainlessInjection
jobs:
    include:
        - osx_image: xcode11.2
          xcode_destination: platform=iOS Simulator,OS=13.2,name=iPhone 8
        - osx_image: xcode11.1
          xcode_destination: platform=iOS Simulator,OS=13.1,name=iPhone 8
after_success:
    - bash <(curl -s https://codecov.io/bash) -t d57dba6a-8e17-4a91-b7bf-ef7abe812e24
install:
    - ./Scripts/install_swiftlint.sh