language: objective-c
osx_image: xcode7.3
notifications:
  email:
    on_success: never
script:
    - xcodebuild clean test -workspace PainlessInjection/PainlessInjection.xcworkspace -scheme PainlessInjection -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty

after_success:
    - pod lib lint --allow-warnings;    